name: velovi-gnn
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.11.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h49ec1c0_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli-python=1.2.0=py311h7c6b74e_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cffi=2.0.0=py311h5b438cf_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py311hc665b79_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h38be061_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.10=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lark=1.3.1=pyhd8ed1ab_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - markupsafe=3.0.3=py311h3778330_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.1.4=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openssl=3.6.0=h26f9b46_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - psutil=7.1.3=py311haee01d2_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=hfe2f287_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311h3778330_0
  - pyzmq=27.1.0=py311h2315fbb_0
  - readline=8.2=h8c095d6_2
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.28.0=py311h902ca64_2
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.18.1=pyh0d859eb_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.2=py311h49ec1c0_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.25.0=py311haee01d2_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - adjusttext==1.3.0
      - aiobotocore==2.25.0
      - aiohttp-retry==2.9.1
      - aioitertools==0.12.0
      - amqp==5.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - asciitree==0.3.3
      - asyncssh==2.21.1
      - atpublic==6.0.2
      - billiard==4.2.2
      - biopython==1.85
      - biothings-client==0.4.1
      - boto3==1.40.49
      - botocore==1.40.49
      - bson==0.5.10
      - captum==0.8.0
      - celery==5.5.3
      - certifi==2025.10.5
      - click==8.2.1
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1.2
      - click-repl==0.3.0
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - configobj==5.0.9
      - contourpy==1.3.3
      - coverage==7.10.7
      - cryptography==46.0.2
      - cycler==0.12.1
      - dask==2024.7.1
      - deprecated==1.2.18
      - dictdiffer==0.9.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dpath==2.2.0
      - dulwich==0.24.3
      - dvc==3.63.0
      - dvc-data==3.16.12
      - dvc-http==2.32.0
      - dvc-objects==5.1.2
      - dvc-render==1.0.2
      - dvc-s3==3.2.2
      - dvc-studio-client==0.22.0
      - dvc-task==0.40.2
      - entrypoints==0.4
      - fasteners==0.20
      - flatten-dict==0.4.2
      - flufl-lock==8.2.0
      - fonttools==4.60.1
      - funcy==2.0
      - future==1.0.0
      - genomepy==0.16.3
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grandalf==0.8
      - gseapy==1.1.11
      - gto==1.9.0
      - h5py==3.15.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - humanize==4.13.0
      - hydra-core==1.3.2
      - hyperopt==0.2.7
      - iterative-telemetry==0.0.10
      - jmespath==1.0.1
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - kombu==5.5.4
      - llvmlite==0.45.1
      - locket==1.0.0
      - loguru==0.7.3
      - loompy==3.0.8
      - louvain==0.8.2
      - markdown==3.9
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - mygene==3.2.2
      - mysql-connector-python==8.4.0
      - networkx==3.5
      - numba==0.62.1
      - numcodecs==0.15.1
      - numpy==1.26.4
      - numpy-groupies==0.11.3
      - nvidia-cublas-cu12==12.8.3.14
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvrtc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.7.1.26
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.9.55
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.8.55
      - omegaconf==2.3.0
      - orjson==3.11.3
      - packaging==24.2
      - partd==1.4.2
      - pathspec==0.12.1
      - pillow==11.3.0
      - plottable==0.1.5
      - pooch==1.8.2
      - py4j==0.10.9.9
      - pyarrow==21.0.0
      - pycparser==2.23
      - pydantic==2.12.1
      - pydantic-core==2.41.3
      - pydantic-settings==2.11.0
      - pydot==4.0.1
      - pyfaidx==0.9.0.3
      - pygit2==1.18.2
      - pygtrie==2.5.0
      - pyparsing==3.2.5
      - pytest-pretty==1.3.0
      - python-dotenv==1.1.1
      - ray==2.50.0
      - rich==14.2.0
      - ruamel-yaml==0.18.15
      - ruamel-yaml-clib==0.2.14
      - s3fs==2025.2.0
      - s3transfer==0.14.0
      - scanpy==1.11.4
      - scib-metrics==0.5.7
      - scikit-learn==1.7.2
      - scikit-misc==0.5.1
      - scipy==1.11.4
      - scmrepo==3.5.2
      - scvelo==0.3.3
      - scvi-tools==1.4.0
      - semver==3.0.4
      - sentry-sdk==2.42.1
      - session-info2==0.2.3
      - shap==0.49.1
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.7.2
      - slicer==0.0.8
      - smmap==5.0.2
      - sqltrie==0.11.2
      - statsmodels==0.14.5
      - sympy==1.13.3
      - tabulate==0.9.0
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - tivelo==0.1.4
      - tomlkit==0.13.3
      - torch==2.7.0+cu128
      - torchaudio==2.7.0+cu128
      - torchvision==0.22.0+cu128
      - tqdm==4.67.1
      - triton==3.3.0
      - typer==0.19.2
      - typing-inspection==0.4.2
      - vine==5.1.0
      - voluptuous==0.15.2
      - wandb==0.22.2
      - wrapt==1.17.3
      - zarr==2.18.7
      - zc-lockfile==4.0
prefix: /gpfs0/bgu-ofircohen/users/likhtepi/conda_dirs/env/velovi-gnn
